# -*- coding: utf-8 -*-
"""3_Colecciones_en_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V825FphBMkPv97zjwOrRWOO8gqi2fAt8
"""

notas = [4.3,5,2.5,4.3,7,1.5]
print(sum(notas)/len(notas))

"""# Introducción
Las colecciones nos permiten agrupar datos, objetos y otras estructuras bajo un mismo nombre.

**¿Ventajas?**

En Python existen cuatro colecciones básicas: Listas, Tuplas, Conjuntos y Diccionarios

## LISTAS

Las listas utilizan corchetes para la creación y acceso de sus elementos

## CREACION Y ACCESO
"""

lenguajes = ["Python", "Java", "Javascript"]
print(lenguajes)
print(lenguajes[0])
print(lenguajes[1])

numeros =  [3,4,6,2,6,8,4,9]
res = numeros[-3] + numeros[5]
print(res)

"""otra forma alternativa de crear listas es mediante la función **list** que recibe como argumento un objeto iterable"""

mi_lista = list('1234567')
milista_eneteros = [int(x) for x in mi_lista]
print(milista_eneteros)
print(mi_lista)

mi_lista = list('1234567')
lista_final = []
for x in mi_lista:
  lista_final.append(int(x))
print(lista_final)

ml = list(range(1,10))
print(ml)

"""Una lista en Python puede almacenar elementos de cualquier tipo de dato, incluso otras listas"""

mi_lista = [2,3.5,True,"amigo", [3,8,"a"]]
print(mi_lista)

mi_listas = [1,2,3, ['p','q', [5,6,7]]]
print(mi_listas[3][2][1])
print(mi_listas[-1][-1][-2])

mi_lista= list(range(1,10))
print(mi_lista)
print(mi_lista [1:4])
print(mi_lista[:2])
print(mi_lista[7:])
print(mi_lista[-5:-1])
print(mi_lista[-3:])

mi_lista = [1,2,3,4,5,6]
mi_lista [0:3] = ["a", "b","c"]
print(mi_lista)

mi_lista = [1,2,3,4,5]
mi_lista = mi_lista  + [6]
print(mi_lista)
mi_lista = mi_lista + [7,8,9]
print(mi_lista)

mi_lista = [1,2,3]
x,y,z = mi_lista # Asignar variables al contenido de la lista
print(f"valor de x: {x}")
print(f"valor de y: {y}")
print(f"valor de z: {z}")

"""## ELIMINACION E INSERCION"""

lenguajes = ["python", "java", "javascript"]
del lenguajes[1]
print(lenguajes)

"""POdemos insertar datos en una posicion especifica  con la funcion insert  o al final de lista con la función append"""

lenguajes = ["python", "java", "javascript"]
lenguajes.insert(1, "c++")
print(lenguajes)
lenguajes.append("c#")
print(lenguajes)

lista = ["casa", "cosa", "ala"]
lista.sort()
print(lista)

"""para saber si un elemento se encuentra dentro de una lista utilizamos la palabra reservada in"""

lenguajes = ["python", "java", "javascript"]
print("python" in lenguajes)
print("c++" in lenguajes)

"""## Recorridos de Listas"""

numeros = [1,2,3,4,5]
print(numeros)
for num in numeros:
  print(num)

"""Python nos ofrece una forma alternativa de acceder al indice de cada elemento a través de la función enumerate"""

numeros = [3,29,34,42,54]
for x,y in enumerate(numeros):
    print(f"EN la posición: {x} encontramos el valor: {y}")

"""Debido a que la función enumerate devuelve para cada elemento de la lista un par (índice - valor), podemos obtener ambos al tiempo en la misma variable como en el ejemplo anterior o acceder a cada uno a través de variables diferentes. Veamos:"""

numeros = ["A", "B", "C", "D", "E"]
for indice,valor in enumerate(numeros):
    print(f"EN la posición: {indice} encontramos el valor: {valor}")

lista = [2,35,8,95,41]
indice = 0
while indice < len(lista):
  print(lista[indice])
  indice += 1

"""Se cuenta con dos listas y se desean recorrer de manera simultánea mostrando el valor de las dos en cada posición.  ¿Ayudarías a terminar el código de tal manera que se obtenga el siguiente resultado?


```
ma - pa
me - pe
mi - pi
mo - po
mu - pu
```
"""

lista_1 = ["ma","me","mi","mo","mu","mu"]
lista_2 = ["pa","pe","pi","po","pu"]

for i in range (min(len(lista_1), len(lista_2))):
  print(lista_1[i] + " - " + lista_2[i])

lista_1 = ["ma","me","mi","mo","mu","ñu"]
lista_2 = ["pa","pe","pi","po","pu"]
lista_3 = ["ra", "re", "ri", "ro", "ru"]
lista_4 = ["sa", "se", "si", "so", "su"]
lista_5 = ["ta", "te", "ti", "to", "tu"]

for x in zip (lista_1, lista_2, lista_3, lista_4, lista_5):
  print(x)

"""A la función **zip** le podemos pasar cualquier número de listas y tendrá la capacidad de generar un iterador que las recorra simultáneamente.

## METODOS APLICABLES A LISTAS
"""



"""El método **sort()** ordena los elementos de una lista"""

mi_lista = [4,5,2,8,2,1]
mi_lista.sort()
print(mi_lista)

"""Podemos pasarle el argumento reverse=True al método sort() para que ordene inversamente"""

mi_lista = [4,5,2,8,2,1]
mi_lista.sort(reverse=True)
print(mi_lista)

"""El método **remove()** recibe como argumento un objeto y lo borra de la lista"""

lenguajes = ["python", "java", "javascript"]
lenguajes.remove("java")
print(lenguajes)

"""Nota que la diferencia entre **remove()** y **del** es que al primero le puedo enviar el valor que deseo remover mientras que el segundo **del** trabaja con los índices"""



"""El método **reverse()** invierte el contenido de la lista"""

lenguajes = ["python", "java", "javascript"]
lenguajes.reverse()
print(lenguajes)

cadena = "HOLA MUNDO"
print(cadena[::-1])

cadena = "HOLA MUNDO0"
Lista = list(cadena)
print(Lista)
Lista.reverse()
print(Lista)

cadena = "".join(Lista)
print(cadena)

"""
```
clear()
Vacía todos los ítems de una lista:
lista.clear()
[]

extend()
Une una lista a otra:
l1 = [1,2,3]
l2 = [4,5,6]
l1.extend(l2)
[1, 2, 3, 4, 5, 6]

count()
Cuenta el número de veces que aparece un ítem:
["Hola", "mundo", "mundo"].count("Hola")
1

index()
Devuelve el índice en el que aparece un ítem (error si no aparece):
["Hola", "mundo", "mundo"].index("mundo")
1

pop()
Extrae un ítem de la lista y lo borra:
l = [10,20,30,40,50]
print(l.pop())
50
[10, 20, 30, 40]

```"""

l = [10,20,30,40,50]
print(l.pop(2))
print(l)

"""## TUPLAS

## Generalidades

Las Tuplas son similares a las listas pero con la característica de ser inmutables, es decir, sus valores no pueden cambiar.  Las Tuplas se crean con paréntesis **()** en lugar de corchetes **[]**  pero al igual que las listas, se accede a sus posiciones con corchetes **[]**  Veamos:
"""

mi_tupla = ("a", "b", "c", "d")
print(type(mi_tupla))
print(mi_tupla)
print(mi_tupla[2])
print(mi_tupla[1:3])
print(mi_tupla[-1])

mi_tupla = ("a", "b", "c", "d")
mi_tupla[1] = "f"
print(mi_tupla[1])

"""**Que ventajas tiene  una Tupla sobre una LIsta**

Las Tuplas al igual que las Listas pueden almacenar diferentes tipos de elementos y pueden conformarse por otras listas o tuplas internas.  El acceso a sus elementos funciona igual que con las listas.
"""

mi_tupla = (100, 'hola', [1,2,3], -50)
print(mi_tupla[2][-1])
mi_tupla = (100, 'hola',(1, (200,'D', ['X', 'Y', 'Z'])), (1,2,3), -50 )
print(mi_tupla[2][1][2][1])

"""Las Tuplas comparten varios métodos de las listas, sin embargo, por ser inmutables, las Tuplas no usan ningún método en cuyo resultado sea un cambio de contenido.  Ejemplo append(), insert(), remove(), sort(), reverse(), etc."""

mi_tupla = (2,5,2,45,12,5,63,52,4,2.5,8,2)
print( mi_tupla.count(2))

mi_tupla = (2,5,2,45,12,5,63,52,4,2.5,8,2)
print(mi_tupla.sort())

"""Las tuplas también las podemos crear a partir de la función **tuple** que recibe un objeto iterable"""

mi_tupla = tuple("Hola Mundo")
print(mi_tupla)
for dato in mi_tupla:
  print(dato)

"""Por lo demás, podemos resumir diciendo que las listas y las tuplas son semejantes, con la diferencia que las segundas no pueden cambiar su contenido."""

mi_tupla = tuple(input("Ingrese una frase: "))
print(mi_tupla)
print(f"La frase tiene {len(mi_tupla)} caracteres")

for dato in mi_tupla:
  print(dato)

for dato in enumerate(mi_tupla):
  print(dato)

"""## PASO DE LA TUPLA A LISTA Y DE LA LISTA A TUPLA"""



"""## Paso de Tupla a Lista y Lista a Tupla
Las funciones **list** y **tuple** son las que nos permiten realizar este tipo de conversiones.  miremos

**Paso de Lista a TUpla**
"""

mi_lista = [1,2,3,4,5]
print(f"{mi_lista} es de tipo {type(mi_lista)}")
mi_tupla = tuple(mi_lista)
print(f"{mi_tupla} es de tipo {type(mi_tupla)}")

"""**Paso de tupla a lista**

"""

mi_tupla = (1,2,3,4,5)
print(f"{mi_tupla} es de tipo {type(mi_tupla)}")
mi_lista = list(mi_tupla)
print(f"{mi_lista} es de tipo {type(mi_lista)}")

mi_tupla = (3,8,5,9,1,4)
mi_lista = list(mi_tupla)
mi_lista.sort()
mi_tupla = tuple(mi_lista)
print(mi_tupla)

"""# APROPIACION

1. Pregunte al usuario cuántos elementos desea ingresar en una lista, luego solicite cada uno de ellos y presente el contenido de la lista y su contenido invertido.

2. Crear una lista de números y solicitar un número.  Borrar de la lista ese número en todas las posiciones donde se encuentre.  Presentar la lista final

3. Solicite al usuario dos(2) frases y devuelva una lista con todas las letras que se repiten en la misma posición de ambas listas

ejemplo:
frase1:  "holasena"
frase2:  "todogana"
salida: ["o","n", "a"]

Pregunte al usuario cuántos elementos desea ingresar en una lista, luego solicite cada uno de ellos y presente el contenido de la lista y su contenido invertido.
"""

mi_lista = list (input("ingrese una frase: "))
print(mi_lista)
print(f"la cantidad de elementos de la tupla es: {len(mi_tupla)}")
for dato in mi_tupla:
  print(dato)

num_elementos = int(input("Ingrese el número de elementos que desea ingresar en la lista: "))
lista = []
for i in range(num_elementos):
    elemento = input(f"Ingrese el elemento {i + 1}: ")
    lista.append(elemento)
print("Contenido de la lista:")
for elemento in lista:
    print(elemento)
print("Contenido de la lista invertido:")
for elemento in reversed(lista):
    print(elemento)

enum_elementos = int(input("Ingrese el número de elementos que desea ingresar en la lista: "))
lista = [input(f"Ingrese el elemento {i + 1}: ") for i in range(num_elementos)]
print("Contenido de la lista:")
print(*lista, sep="\n")
print("Contenido de la lista invertido:")
print(*reversed(lista), sep="\n")

num_elementos = int(input("Ingrese el número de elementos que desea ingresar en la lista: "))
lista = [input(f"Ingrese el elemento {i + 1}: ") for i in range(num_elementos)]
print("\nContenido de la lista:\n", *lista, sep="\n")
print("\nContenido de la lista invertido:\n", *lista[::-1], sep="\n")

"""Crear una lista de números y solicitar un número. Borrar de la lista ese número en todas las posiciones donde se encuentre. Presentar la lista final"""

num_elementos = int(input("Ingrese el número de elementos que desea ingresar en la lista: "))
lista = []
for i in range(num_elementos):
    elemento = int(input(f"Ingrese el elemento {i + 1}: "))
    lista.append(elemento)
print("Contenido de la lista:")
for elemento in lista:
    print(lista)
    print("Contenido de la lista invertido:")
    print(lista[::-1])



num_elementos = int(input("Ingrese el número de elementos que desea ingresar en la lista: "))
lista = []
for i in range(num_elementos):
    elemento = input(f"Ingrese el elemento {i + 1}: ")
    lista.append(elemento)
print("Contenido de la lista:")
for elemento in lista:
    print(elemento)
print("Contenido de la lista invertido:")
for elemento in reversed(lista):
    print(elemento)

numeros = [1, 2, 3, 4, 5, 2, 3, 6, 2, 7]
numero_eliminar = int(input("Ingrese el número que desea eliminar: "))
numeros = [x for x in numeros if x != numero_eliminar]
print("Lista final:", numeros)

frase1 = input("Ingrese la primera frase: ")
frase2 = input("Ingrese la segunda frase: ")
if len(frase1) != len(frase2):
    print("Las frases deben tener la misma longitud")
else:
    letras_repetidas = []
    for i in range(len(frase1)):
        if frase1[i] == frase2[i]:
            letras_repetidas.append(frase1[i])
    print("Letras que se repiten en la misma posición:", letras_repetidas)